<!-- bottom Banners -->
<div class="bgDark">
	<div class="container">
		<section class="row banners">
			<div class="col-md-4 banner">
				<a href="newsletters" title="inscríbete y te regalamos 10€">
					<img class="img-responsive" src="imagenes/loader.gif" data-src="imagenes/banners/inscribete.jpg" alt="inscríbete y te regalamos 10€">
					<span>Inscríbete y te regalamos 10€</span>
				</a>
			</div>
			<div class="col-md-4 banner">
				<a href="registro?tipo=pro" title="¿eres profesional? Regístrate aquí">
					<img class="img-responsive" src="imagenes/loader.gif" data-src="imagenes/banners/profesional.jpg" alt="¿eres profesional? Regístrate aquí">
					<span>¿Eres profesional? Regístrate aquí</span>
				</a>
			</div>
			<div class="col-md-4 banner">
				<a href="shipping" title="Enviamos a toda Europa">
					<img class="img-responsive" src="imagenes/loader.gif" data-src="imagenes/banners/envios.jpg" alt="Enviamos a toda Europa">
					<span>Enviamos a toda Europa</span>
				</a>
			</div>
			<div class="col-xs-12 hidden-xs banner puntos-de-venta">
				<a href="showrooms" title="puntos de venta">
					<img class="img-responsive" src="imagenes/loader.gif" data-src="imagenes/banners/puntosventa.jpg" alt="puntos de venta">
					<button class="btn btn-default btn-rounded">puntos de venta</button>
				</a>
		</section>
	</div>
</div>