<!-- Designers -->
<div class="container">
    <section class="row collapsed designers" id="designers">
        <h5 class="title">diseñadores</h5>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Arne Jacobsen</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/Jacobsen.jpg') ?>" srcset="<?php echo $this->getSkinUrl('images/disenadores/Jacobsen@2x.jpg') ?> 2x"
                     alt="Arne Jacobsen">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Charles & Ray Eames</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/Eames.jpg') ?>" srcset="<?php echo $this->getSkinUrl('images/disenadores/Eames@2x.jpg') ?> 2x"
                     alt="Charles & Ray Eames">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Eero Aarnio</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/EeroAarnio.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/EeroAarnio@2x.jpg') ?> 2x" alt="Eero Aarnio">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Eero Saarinen</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/EeroSaarinen.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/EeroSaarinen@2x.jpg') ?> 2x" alt="Eero Saarinen">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Eileen Gray</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/EileenGray.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/EileenGray@2x.jpg') ?> 2x" alt="Eileen Gray">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Florence Knoll</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/FlorenceKnoll.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/FlorenceKnoll@2x.jpg') ?> 2x" alt="Florence Knoll">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Harry Bertoia</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/HarryBertoia.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/HarryBertoia@2x.jpg') ?> 2x" alt="Harry Bertoia">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Isamu Noguchi</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/IsamuNoguchi.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/IsamuNoguchi@2x.jpg') ?> 2x" alt="Isamu Noguchi">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Jean Prouvé</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/JeanProuve.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/JeanProuve@2x.jpg') ?> 2x" alt="Jean Prouvé">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Le Corbusier</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/LeCorbusier.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/LeCorbusier@2x.jpg') ?> 2x" alt="Le Corbusier">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Marcel Breuer</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/MarcelBreuer.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/MarcelBreuer@2x.jpg') ?> 2x" alt="Marcel Breuer">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Mies van der Rohe</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/VanDerRohe.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/VanDerRohe@2x.jpg') ?> 2x" alt="Mies van der Rohe">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Philippe Starck</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/PhilippeStarck.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/PhilippeStarck@2x.jpg') ?> 2x" alt="Philippe Starck">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Achille & Pier Castiglioni</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/Achille.jpg') ?>" srcset="<?php echo $this->getSkinUrl('images/disenadores/Achille@2x.jpg') ?> 2x"
                     alt="Achille & Pier Castiglioni">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Tom Dixon</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/TomDixon.jpg') ?>" srcset="<?php echo $this->getSkinUrl('images/disenadores/TomDixon@2x.jpg') ?> 2x"
                     alt="Tom Dixon">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Verner Panton</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/VernerPanton.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/VernerPanton@2x.jpg') ?> 2x" alt="Verner Panton">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Serge Mouille</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/SergeMouille.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/SergeMouille@2x.jpg') ?> 2x" alt="Serge Mouille">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Xavier Pauchard</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/disenadores/XavierPauchard.jpg') ?>"
                     srcset="<?php echo $this->getSkinUrl('images/disenadores/XavierPauchard@2x.jpg') ?> 2x" alt="Xavier Pauchard">
            </a>
        </div>
        <div class="col-md-12 read-more">
            <button class="btn btn-default btn-rounded toggle-height" data-element="designers" data-action="show">VER MÁS</button>
            <button class="btn btn-default btn-rounded toggle-height hide" data-element="designers" data-action="hide">VER MENOS</button>
        </div>
    </section>
</div>

<!-- Styles -->
<div class="container">
    <section class="row styles" id="styles">
        <h5 class="title">Estilos</h5>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Tolix Design</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/tolix-design.jpg') ?>" srcset="<?php echo $this->getSkinUrl('imagenes/colecciones/tolix-design@2x.jpg') ?> 2x" alt="Tolix Design">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Tower Design</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/iluminacion.jpg') ?>" srcset="imagenes/colecciones/iluminacion@2x.jpg 2x" alt="Tower Design">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Modern Classics</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/lienzos-vinilos.jpg') ?>" srcset="imagenes/colecciones/lienzos-vinilos@2x.jpg 2x" alt="Modern Classics">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Pop</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/pop.jpg') ?>" srcset="imagenes/colecciones/pop@2x.jpg 2x" alt="Pop">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Color edition</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/pop.jpg') ?>" srcset="imagenes/colecciones/pop@2x.jpg 2x" alt="Color edition">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Transparente</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/pop.jpg') ?>" srcset="imagenes/colecciones/pop@2x.jpg 2x" alt="Transparente">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Vintage</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/vintage.jpg') ?>" srcset="imagenes/colecciones/vintage@2x.jpg 2x"
                     alt="Vintage">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Rústico</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/rustico.jpg') ?>" srcset="imagenes/colecciones/rustico@2x.jpg 2x"
                     alt="Rústico">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Industrial</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/industrial.jpg') ?>" srcset="imagenes/colecciones/industrial@2x.jpg 2x" alt="Industrial">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Nórdico</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/nordico.jpg') ?>" srcset="imagenes/colecciones/nordico@2x.jpg 2x" alt="Nórdico">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>New York</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/new-york.jpg') ?>" srcset="imagenes/colecciones/new-york@2x.jpg 2x" alt="New York">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Objeto decorativo</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/objeto-decorativo.jpg') ?>" srcset="imagenes/colecciones/objeto-decorativo@2x.jpg 2x" alt="Objeto decorativo">
            </a>
        </div>
        <div class="col-md-12 read-more">
            <button class="btn btn-default btn-rounded toggle-height" data-element="styles" data-action="show">VER MÁS</button>
            <button class="btn btn-default btn-rounded toggle-height hide" data-element="styles" data-action="hide">VER MENOS</button>
        </div>
    </section>
</div>

<!-- Colections -->
<div class="container">
    <section class="row colections" id="colections">
        <h5 class="title">Colecciones</h5>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Baño</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/bano.jpg') ?>" srcset="<?php echo $this->getSkinUrl('images/colecciones/bano@2x.jpg') ?> 2x" alt="Baño">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Cocina</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/cocina.jpg') ?>" srcset="<?php echo $this->getSkinUrl('images/colecciones/cocina@2x.jpg') ?> 2x" alt="Cocina">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Trabajo</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/trabajo.jpg') ?>" srcset="<?php echo $this->getSkinUrl('images/colecciones/trabajo@2x.jpg') ?> 2x" alt="Trabajo">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Descanso</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/descanso.jpg') ?>" srcset="<?php echo $this->getSkinUrl('images/colecciones/descanso@2x.jpg') ?> 2x" alt="Descanso">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Dormitorio</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/dormitorio.jpg') ?>" srcset="<?php echo $this->getSkinUrl('images/colecciones/dormitorio@2x.jpg') ?> 2x" alt="Dormitorio">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Niños</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/ninos.jpg') ?>" srcset="<?php echo $this->getSkinUrl('images/colecciones/ninos@2x.jpg') ?> 2x" alt="Niños">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Verano</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/verano.jpg') ?>" srcset="<?php echo $this->getSkinUrl('images/colecciones/verano@2x.jpg') ?> 2x" alt="Verano">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>Navidad</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/navidad.jpg') ?>" srcset="<?php echo $this->getSkinUrl('images/colecciones/navidad@2x.jpg') ?> 2x" alt="Navidad">
            </a>
        </div>
        <div class="col-xs-6 col-md-3">
            <a href="#">
                <h6>San Valentín</h6>
                <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/colecciones/san-valentin.jpg') ?>" srcset="<?php echo $this->getSkinUrl('images/colecciones/san-valentin@2x.jpg') ?> 2x" alt="San Valentín">
            </a>
        </div>
        <div class="col-md-12 read-more">
            <button class="btn btn-default btn-rounded toggle-height" data-element="colections" data-action="show">VER MÁS</button>
            <button class="btn btn-default btn-rounded toggle-height hide" data-element="colections" data-action="hide">VER MENOS</button>
        </div>
    </section>
</div>