<section class="row banners-principales">
	<div class="col-md-6">
		<a href="#">
			<img class="img-responsive" alt="Sillas DSW a mitad de precio" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/banners/sillasdsw.jpg') ?>" />
		</a>
		<div id="countdown1" class="countdown">&nbsp;</div>
	</div>
	<div class="col-md-6">
		<a href="#">
			<img class="img-responsive" alt="Precio m&iacute;nimo garantizado" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/banners/preciominimo1.jpg') ?>" />
		</a>
		<div id="countdown2" class="countdown">&nbsp;</div>
		<a href="#">
			<img class="img-responsive" alt="Semana sin IVA" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/banners/semanaiva.png') ?>" />
		</a>
		<div id="countdown3" class="countdown">&nbsp;</div>
	</div>
</section>