<!-- Ventajas -->
<section class="ventajas">
	<div class="container">
		<div class="row text-center">
			<div class="col-xs-6 col-md-3">
				<img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/iconos/svg/ventajasCorazon.svg') ?>" alt="ventajas icono">
				<h4>Diseño</h4>
				<p>El mejor diseño al mejor precio y todo el estilo en un sólo lugar.</p>
			</div>
			<div class="col-xs-6 col-md-3">
				<img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/iconos/svg/ventajasSSL.svg') ?>" alt="SSL icono">
				<h4>Compra segura</h4>
				<p>Tienda online con protocolo SSl para realizar tus compras con seguridad.</p>
			</div>
			<div class="col-xs-6 col-md-3">
				<img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/iconos/svg/ventajasStock.svg') ?>" alt="envío icono">
				<h4>Gran stock</h4>
				<p>Nuestro gran stock te asegura un servicio de entrega rápida.</p>
			</div>
			<div class="col-xs-6 col-md-3">
				<img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/iconos/svg/ventajasChat.svg') ?>" alt="chat icono">
				<h4>Estamos cerca</h4>
				<p>Si tienes cualquier duda, estamos cerca para asesorarte.</p>
			</div>
		</div>
	</div>
</section>

<!-- Métodos de pago -->
<section class="methods-and-quality">
	<div class="container">
		<div class="row text-center metodo-pago">
			<h4>Métodos de pago</h4>
			<ul>
				<li class="pagos visa"></li>
				<li class="pagos visa-electron"></li>
				<li class="pagos mastercard"></li>
				<li class="pagos maestro"></li>
				<li class="pagos american-express"></li>
				<li class="pagos aplazame"></li>
				<li class="pagos skrill"></li>
				<li class="pagos ideal"></li>
				<li class="pagos giropay"></li>
				<li class="pagos postepay"></li>
				<li class="pagos trustly"></li>
				<li class="pagos sofort-banking"></li>
				<li class="pagos cb"></li>
				<li class="pagos eps"></li>
				<li class="pagos bank-transfer"></li>
				<li class="pagos cod"></li>
			</ul>
		</div>

		<div class="row text-center calidad-y-confianza">
			<h4>Seguridad y calidad</h4>
			<ul>
				<li class="pagos rapid-ssl"></li>
			</ul>
		</div>
	</div>
</section>

<!-- Contacto -->
<section class="ventajas">
	<div class="container">
		<div class="row text-center">
			<div class="col-xs-6 col-md-3">
				<img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/iconos/svg/ventajasEscribenos.svg') ?>" alt="escríbenos icono">
				<h4>Escríbenos</h4>
				<p><a href="contacto.html" title="Contacta con nosotros">Contacta con nosotros</a></p>
			</div>
			<div class="col-xs-6 col-md-3">
				<img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/iconos/svg/ventajasLlamanos.svg')		 ?>" alt="llámanos icono">
				<h4>Llámanos</h4>
				<p>Teléfono +34 932 417 330</p>
			</div>
			<div class="col-xs-6 col-md-3">
				<img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/iconos/svg/ventajasEnvio.svg') ?>" alt="envío icono">
				<h4>Costes de envío</h4>
				<p><a href="shipping.html" title="enviamos a toda Europa">¡Enviamos a toda Europa!</a></p>
			</div>
			<div class="col-xs-6 col-md-3">
				<img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/iconos/svg/ventajasDevoluciones.svg') ?>" alt="devoluciones icono">
				<h4>Devoluciones</h4>
				<p>Consulta aquí las <a href="condiciones.html" title="condiciones de uso">condiciones</a></p>
			</div>
		</div>
	</div>
</section>

<!-- Newsletter y Redes Sociales -->
<div class="bgDark">
	<div class="container">
		<section class="newsletter">
			<div class="row footer-top">
				<div class="col-md-6 text-center">
					<h4>¿Quieres recibir <br>nuestras newsletter?</h4>
					<div id="step1">
						<form id="footerNewsletterForm" class="footer-newsletter-form" method="post">
							<input type="hidden" name="datos" value="1">
							<input type="hidden" name="outlet" value="">
							<div class="input-group">
								<input id="footerEmailInput" name="email_newsletter" type="email" class="form-control" required>
								<span class="input-group-btn">
									<input class="btn btn-flat" type="submit" value="Inscribirse"/>
								</span>
						    </div>
							<span id="helpBlockEmpty" class="help-block hidden">Debes introducir un email</span>
							<span id="helpBlockExist" class="help-block hidden">Este email ya existe</span>
							<span id="helpBlockError" class="help-block hidden">El email no es válido</span>
						    <small>Con el envío de mis datos confirmo que he leído y acepto la <a href="privacidad.html" title="política de privacidad">política de privacidad</a>.</small>
						</form>
					</div>
					<div id="step2" class="step-2">
						<p class="bg-success">Gracias por registrarte<br />
						En unos minutos te llegará un email para obtener tu descuento.</p>
						<small>Revisa la carpeta Spam de tu correo si no lo recibes.</small>
					</div>
				</div>
				<div class="col-md-6 text-center">
					<h4>Siguenos para no perderte nuestras <br>novedades y promociones</h4>
					<a class="enlaces_sociales" href="https://www.facebook.com/SuperStudioFanPage" target="_blank">
						<img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/iconos/svg/smFacebook.svg') ?>" alt="facebook icono">
					</a>
					<a class="enlaces_sociales" href="https://twitter.com/superstudioweb" target="_blank">
						<img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/iconos/svg/smTwitter.svg') ?>" alt="twitter icono">
					</a>
					<a class="enlaces_sociales" href="https://plus.google.com/+SuperestudioES/posts" target="_blank">
						<img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/iconos/svg/smGoogle.svg') ?>" alt="googleplus icono">
					</a>
					<a class="enlaces_sociales" href="https://www.pinterest.com/superstudioweb/" target="_blank">
						<img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/iconos/svg/smPinterest.svg') ?>" alt="pinterest icono">
					</a>
					<a class="enlaces_sociales" href="https://www.youtube.com/channel/UC7WlxvGU_b7FXo77cn0UiJA" target="_blank">
						<img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/iconos/svg/smYoutube.svg') ?>" alt="youtube icono">
					</a>
				</div>
			</div>
		</section>
	</div>
</div>