<!-- Especiales -->
<section class="row banners-especial">
	<div class="col-md-4 banner banner-eames">
		<div class="banner-img"><img class="img-responsive" alt="banner eames" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/banners/eames.jpg') ?>" />
			<div class="titulo">Especial <span>Eames design</span></div>
		</div>
	</div>
	<div class="col-md-4 banner banner-tolix">
		<div class="banner-img">
			<img class="img-responsive" alt="banner packs" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/banners/packs.jpg') ?>" />
			<div class="titulo">Ofertas especiales en <span>Packs</span></div>
		</div>
	</div>
	<div class="col-md-4 banner banner-pop">
		<div class="banner-img">
			<img class="img-responsive" alt="banner precio m&iacute;nimo" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->getSkinUrl('images/banners/preciominimo3.jpg') ?>" />
			<div class="titulo">Precio m&iacute;nimo <span>garantizado</span></div>
			<span class="footer-text">en m&aacute;s de 60 productos</span>
		</div>
	</div>
</section>