<!-- Preloader -->
<div id="preloader" class="ui-blocker">
	<div class="thecube">
		<div class="cube c1"></div>
		<div class="cube c2"></div>
		<div class="cube c4"></div>
		<div class="cube c3"></div>
	</div>
</div>

<!-- Scroll to top arrow -->
<button id="scrollToTopBtn" class="btn scroll-to-top-btn"><span class="glyphicon glyphicon-chevron-up"></span></button>

<!-- Start of Logging Code  -->
<script data-main="<?php echo $this->getSkinUrl('js/default.js') ?>" src="<?php echo $this->getSkinUrl('js/lib/require.min.js') ?>"></script>
